# Generated by Django 4.1.7 on 2023-03-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('message', models.TextField(verbose_name='پیام')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('mail', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
